-- 語彙ハブ最小 schema (P2 / DD-DICT-008 v0.2 + 34_vocabulary_layer)
-- doc: design/vocab_object/03_P2_VOCAB_SCHEMA_DEPLOY_PLAN
-- STATUS: 設計生成物 / 未 apply. owner GO + GPT独立監査 + canary→batch が必須.
-- DB: PostgreSQL / Supabase. append-only 設計(term は valid_to で論理失効).
-- 不変条件: 全 hub は既定 provisional. canonical 昇格は P3 人手 + 入口ゲート通過後のみ.

begin;

-- 1. 概念スキーム (rank 体系: 100/100a-100d/101/102/103-107/200)
create table if not exists alo_concept_schemes (
    scheme_id        text primary key,
    name             text not null,
    authority_rank   text not null,                 -- '100','100a'..'102','103'.. ,'200'
    role             text not null default 'bedrock',-- bedrock / specialty / bibliographic
    ingest_policy    text not null default 'attach', -- seed(bedrock) / attach(specialty)
    created_at       timestamptz not null default now()
);

-- 2. Term = 語義単位
create table if not exists alo_terms (
    term_id          text primary key,
    scheme_id        text not null references alo_concept_schemes(scheme_id),
    normalized_pref  text not null,
    reading          text,
    definition       text,
    term_tier        smallint not null default 1,
    source_item_key  text,
    -- 品質メタ (P0 ツール群由来: 06-11 findings)
    reading_source   text,                           -- original/kana_infer/yuhikaku_pref_match/pykakasi
    def_quality      text,                           -- ok/empty/cross_reference/valid_short/truncation/other
                                                      -- (短定義は short_def_triage の4分類値, 長定義は ok)
    valid_from       timestamptz not null default now(),
    valid_to         timestamptz,                    -- 論理失効 (append-only)
    created_at       timestamptz not null default now()
);
create index if not exists idx_alo_terms_key   on alo_terms (normalized_pref, reading);
create index if not exists idx_alo_terms_scheme on alo_terms (scheme_id);
create index if not exists idx_alo_terms_live   on alo_terms (term_id) where valid_to is null;

-- 3. Term ラベル (別表記/読み/別名 surface form)
create table if not exists alo_term_labels (
    id          bigint generated by default as identity primary key,
    term_id     text not null references alo_terms(term_id),
    label       text not null,
    label_type  text not null default 'alt'         -- pref/reading/alt/abbrev
);
create index if not exists idx_alo_term_labels_term on alo_term_labels (term_id);

-- 4. Hub = 概念ノード (既定 provisional)
create table if not exists alo_hubs (
    hub_id              text primary key,
    anchor_term_id      text not null references alo_terms(term_id),
    hub_label           text not null,
    reading             text,
    hub_status          text not null default 'provisional',   -- provisional / canonical(P3のみ)
    identity_scope      text not null default 'vocab_hub_provisional_noncanonical',
    -- 品質メタ
    needs_preprocessing text[] not null default '{}',          -- ['empty_def']['short_def'] 等. 非空=canonical不可
    homograph_genuine   boolean not null default false,        -- defrag が保持した真の同綴異義(参議等)
    created_at          timestamptz not null default now(),
    constraint chk_hub_status check (hub_status in ('provisional','canonical'))
);
create index if not exists idx_alo_hubs_anchor on alo_hubs (anchor_term_id);

-- 5. Hub メンバーシップ (Term -> Hub)
create table if not exists alo_hub_memberships (
    hub_id           text not null references alo_hubs(hub_id),
    term_id          text not null references alo_terms(term_id),
    map_type         text not null,                  -- bedrock_seed/skos_exact_match/homograph_split/
                                                     -- reading_missing_def_match/skos_close_match/specialty_seed
    is_anchor        boolean not null default false,
    definition_overlap numeric,
    primary key (hub_id, term_id)
);
create index if not exists idx_alo_memberships_term on alo_hub_memberships (term_id);

-- 6. Term 間関係 (別名/参照: cross_reference 363 を収容)
create table if not exists alo_term_relations (
    id            bigint generated by default as identity primary key,
    src_term_id   text not null references alo_terms(term_id),
    dst_term_id   text references alo_terms(term_id),  -- 未解決(別辞書)は null 可+dst_label
    dst_label     text,                                -- 解決前の target 見出し
    relation_type text not null,                       -- alias_of / see_also / skos_related
    source        text default 'xref_extract',
    constraint chk_relation_type check (relation_type in ('alias_of','see_also','skos_related'))
);
create index if not exists idx_alo_relations_src on alo_term_relations (src_term_id);

-- 7. Entity links (legal WSD: P3 / DD-EL-001. P2 では空でよい)
create table if not exists alo_entity_links (
    mention_id      text primary key,
    target_term_id  text references alo_terms(term_id),
    target_hub_id   text references alo_hubs(hub_id),
    confidence      numeric,
    method          text,                            -- P3で埋める
    created_at      timestamptz not null default now()
);

commit;
